import { databasePool } from "../config/database.js";
import { getCourseById, getCourseMembers } from "./course-service.js";
import { getPublicUserById } from "./user-service.js";
import { createLmsNotification } from "./notification-service.js";

const text = value => typeof value === "string" ? value.trim() : "";
const valid = payload => text(payload?.subject).length > 0 && text(payload?.subject).length <= 120 && text(payload?.body).length > 0 && text(payload?.body).length <= 2000;
const row = value => value ? { id: String(value.id), courseId: String(value.course_id), senderId: String(value.sender_reference), recipientId: String(value.recipient_reference), type: String(value.message_type), subject: String(value.subject), body: String(value.body), createdAt: new Date(value.created_at).toISOString(), readAt: value.read_at ? new Date(value.read_at).toISOString() : null } : null;
async function user(id, query) { return getPublicUserById(id, { query }); }
async function courseForTeacher(teacherId, courseId, query) { const course = await getCourseById(courseId, { query }); return course?.teacherReference === teacherId ? course : null; }

export async function sendCourseMessage(teacherId, courseId, payload = {}, { query = databasePool.query.bind(databasePool) } = {}) {
  const teacher = await user(teacherId, query); if (!teacher || teacher.role !== "TEACHER") return { sent: false, code: teacher ? "TEACHER_ROLE_REQUIRED" : "USER_NOT_FOUND", messages: [] };
  const course = await courseForTeacher(teacher.id, courseId, query); if (!course) return { sent: false, code: "COURSE_ACCESS_DENIED", messages: [] };
  if (!valid(payload)) return { sent: false, code: "INVALID_MESSAGE", messages: [] };
  const recipients = await getCourseMembers(course.id, { query }); if (!recipients.length) return { sent: false, code: "NO_RECIPIENTS", messages: [] };
  const messages = []; for (const recipient of recipients) { const result = await query("INSERT INTO lms_messages (course_id,sender_reference,recipient_reference,message_type,subject,body) VALUES ($1,$2,$3,'COURSE',$4,$5) RETURNING id,course_id,sender_reference,recipient_reference,message_type,subject,body,created_at,read_at", [course.id, teacher.id, recipient.id, text(payload.subject), text(payload.body)]); const created = row(result.rows[0]); messages.push(created); await createLmsNotification(recipient.id, { type: "MESSAGE", title: "Nuevo mensaje del curso", message: created.subject, severity: "INFO", resourceType: "MESSAGE", resourceReference: created.id }, { query }).catch(() => null); }
  return { sent: true, code: null, messages };
}
export async function sendMessage(senderId, payload = {}, options = {}) { return sendCourseMessage(senderId, payload.courseId, payload, options); }
export async function getMessagesForUser(userId, { query = databasePool.query.bind(databasePool) } = {}) { const current = await user(userId, query); if (!current || current.role === "ADMIN") return { authorized: false, code: current ? "ROLE_NOT_ALLOWED" : "USER_NOT_FOUND", messages: [] }; const where = current.role === "TEACHER" ? "sender_reference" : "recipient_reference"; const result = await query(`SELECT id,course_id,sender_reference,recipient_reference,message_type,subject,body,created_at,read_at FROM lms_messages WHERE ${where}=$1 ORDER BY created_at DESC`, [current.id]); return { authorized: true, code: null, messages: result.rows.map(row).filter(Boolean) }; }
export async function getMessageById(userId, messageId, { query = databasePool.query.bind(databasePool) } = {}) { const current = await user(userId, query); if (!current || current.role === "ADMIN") return { authorized: false, code: current ? "ROLE_NOT_ALLOWED" : "USER_NOT_FOUND", message: null }; const result = await query("SELECT id,course_id,sender_reference,recipient_reference,message_type,subject,body,created_at,read_at FROM lms_messages WHERE id::text=$1 LIMIT 1", [text(messageId)]); const message = row(result.rows[0]); const allowed = message && (current.role === "TEACHER" ? message.senderId === current.id : message.recipientId === current.id); return { authorized: Boolean(allowed), code: allowed ? null : "MESSAGE_NOT_FOUND", message: allowed ? message : null };
}
export async function markMessageAsRead(userId, messageId, { query = databasePool.query.bind(databasePool) } = {}) { const found = await getMessageById(userId, messageId, { query }); if (!found.authorized) return { updated: false, code: found.code, message: null }; const current = await user(userId, query); if (current.role !== "STUDENT") return { updated: false, code: "STUDENT_ROLE_REQUIRED", message: null }; if (found.message.readAt) return { updated: true, code: null, message: found.message }; const result = await query("UPDATE lms_messages SET read_at=NOW() WHERE id=$1 AND recipient_reference=$2 RETURNING id,course_id,sender_reference,recipient_reference,message_type,subject,body,created_at,read_at", [found.message.id, current.id]); return { updated: true, code: null, message: row(result.rows[0]) };
}
export async function getUnreadCount(userId, { query = databasePool.query.bind(databasePool) } = {}) { const current = await user(userId, query); if (!current || current.role !== "STUDENT") return { authorized: false, code: current ? "STUDENT_ROLE_REQUIRED" : "USER_NOT_FOUND", count: 0 }; const result = await query("SELECT COUNT(*)::int AS count FROM lms_messages WHERE recipient_reference=$1 AND read_at IS NULL", [current.id]); return { authorized: true, code: null, count: Number(result.rows[0]?.count || 0) }; }
