// Interfaz DEMO aislada de Emergencias UBO. Solo consulta y prepara objetos en memoria.
import { getEmergencies, getEmergencyById, getEmergencyStatistics } from "../../../services/emergency-service.js";
import { getAvailableEmergencyActions, prepareEmergencyAction, prepareEmergencyReport, prepareEmergencyAcknowledgement, prepareEmergencyStatusUpdate, validateEmergencyAction } from "../../../services/emergency-actions/emergency-action-service.js";

const $ = s => document.querySelector(s);
const actors = { STUDENT: { id: "student-sofia-martinez", role: "STUDENT", name: "Sofía Martínez" }, TEACHER: { id: "teacher-carlos-perez", role: "TEACHER", name: "Carlos Pérez" }, ADMIN: { id: "admin-ubo", role: "ADMIN", name: "Administrador UBO" } };
const statuses = ["reported", "acknowledged", "in-progress", "resolved", "cancelled"];
let role = "STUDENT", query = "", statusFilter = "all", severityFilter = "all", typeFilter = "all";
const esc = v => String(v ?? "Sin información disponible").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;");
const actor = () => actors[role];
const pretty = value => ({"in-progress":"En progreso",acknowledged:"Reconocida",reported:"Reportada",resolved:"Resuelta",cancelled:"Cancelada",critical:"Crítica",high:"Alta",medium:"Media",low:"Baja"})[value] || value;
const date = value => value ? new Date(value).toLocaleString("es-CL", { dateStyle:"medium", timeStyle:"short" }) : "Sin información disponible";
function message(text="", type="") { const el=$("#message"); el.textContent=text; el.className=`message ${type}`; }
function catalogTypes() { return [...new Set(getEmergencies().map(emergency => emergency.type).filter(Boolean))]; }
function renderTypeFilter() { const filter=$("#type-filter"); const types=catalogTypes(); if(!types.includes(typeFilter)) typeFilter="all"; filter.innerHTML=`<option value="all">Todos</option>${types.map(type=>`<option value="${esc(type)}">${esc(type)}</option>`).join("")}`; filter.value=typeFilter; }
function visible() { return getEmergencies().filter(e => (statusFilter==="all"||e.status===statusFilter) && (severityFilter==="all"||e.severity===severityFilter) && (typeFilter==="all"||e.type===typeFilter) && `${e.title} ${e.description} ${e.location} ${e.type}`.toLowerCase().includes(query.toLowerCase().trim())); }
function statistics() { const s=getEmergencyStatistics(); [["total",s.total],["reported",s.reported],["ack",s.acknowledged],["progress",s.inProgress],["resolved",s.resolved],["cancelled",s.cancelled],["critical",s.critical],["high",s.high]].forEach(([id,value])=>$("#stat-"+id).textContent=value); }
function transitions(e) { if(role!=="ADMIN") return []; return statuses.filter(newStatus => validateEmergencyAction({actor:actor(),action:"update-emergency-status",emergencyId:e.id,userId:actor().id,newStatus}).valid); }
function actionMarkup(e) { const own=e.reportedBy===actor().id; let buttons=`<button class="text" data-action="detail" data-id="${esc(e.id)}">Ver detalle</button>`; if(role!=="ADMIN" && own) buttons+=`<button class="text" data-action="consult" data-id="${esc(e.id)}">Consultar</button>`; if(role==="ADMIN") { if(validateEmergencyAction({actor:actor(),action:"consult-emergency",emergencyId:e.id}).valid) buttons+=`<button class="text" data-action="consult" data-id="${esc(e.id)}">Consultar</button>`; if(validateEmergencyAction({actor:actor(),action:"acknowledge-emergency",emergencyId:e.id,userId:actor().id}).valid) buttons+=`<button class="secondary" data-action="ack" data-id="${esc(e.id)}">Preparar reconocimiento</button>`; const options=transitions(e); if(options.length) buttons+=`<label class="transition">Nuevo estado<select data-transition="${esc(e.id)}">${options.map(x=>`<option value="${x}">${pretty(x)}</option>`).join("")}</select><button class="secondary" data-action="update" data-id="${esc(e.id)}">Preparar actualización</button></label>`; } return buttons; }
function render() { const items=visible(); $("#catalog-context").textContent=role==="ADMIN"?"Vista institucional DEMO de solo lectura.":"Consulta de emergencias DEMO propias."; $("#emergency-list").innerHTML=items.length?items.map(e=>`<article class="card severity-${e.severity}"><div class="badges"><span class="badge severity">${esc(pretty(e.severity))}</span><span class="badge state">${esc(pretty(e.status))}</span></div><h3>${esc(e.title)}</h3><p>${esc(e.description)}</p><dl><div><dt>Tipo</dt><dd>${esc(e.type)}</dd></div><div><dt>Ubicación</dt><dd>${esc(e.location)}</dd></div><div><dt>Reporter</dt><dd>${esc(e.reportedBy)}</dd></div><div><dt>Reporte</dt><dd>${esc(date(e.reportedAt))}</dd></div></dl><div class="actions">${actionMarkup(e)}</div></article>`).join(""):`<p class="empty">No hay emergencias para los filtros seleccionados.</p>`; }
function roleInfo() { const available=getAvailableEmergencyActions().filter(a=>a.roles.includes(role)); $("#selected-user").textContent=`${actor().name} · ${role}`; $("#role-info").innerHTML=role==="ADMIN"?`<b>${available.length} acciones disponibles.</b><span>Gestión futura: requiere fuente institucional.</span>`:`<b>${available.length} acciones disponibles.</b><span>Las preparaciones no cambian registros.</span>`; const admin=role==="ADMIN"; $("#report-button").disabled=admin; $("#report-restriction").hidden=!admin; $("#requires-source").hidden=!admin; }
function detail(id) { const e=getEmergencyById(id); if(!e) return message("La emergencia no existe.","error"); const fields=[["Título",e.title],["Descripción",e.description],["Tipo",e.type],["Severidad",pretty(e.severity)],["Estado",pretty(e.status)],["Ubicación",e.location],["Reporter",e.reportedBy],["Reportada",date(e.reportedAt)],["Resuelta",date(e.resolvedAt)],["Instrucciones",e.instructions]]; $("#detail-content").innerHTML=fields.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join(""); $("#detail-dialog").showModal(); }
function prepared(result, ok) { if(!result.prepared) return message(result.warning||"No fue posible preparar la acción.","error"); message(`${ok} Operación preparada — no aplicada ni almacenada.`,"success"); statistics(); render(); }
function handle(action,id) { if(action==="detail") return detail(id); if(action==="consult") return prepared(prepareEmergencyAction({actor:actor(),action:"consult-emergency",emergencyId:id}),"Consulta DEMO preparada."); if(action==="ack") return prepared(prepareEmergencyAcknowledgement({actor:actor(),emergencyId:id,userId:actor().id}),"Reconocimiento DEMO preparado — no aplicado."); if(action==="update") { const selected=document.querySelector(`[data-transition="${id}"]`); return prepared(prepareEmergencyStatusUpdate({actor:actor(),emergencyId:id,userId:actor().id,newStatus:selected?.value}),"Actualización DEMO preparada — no aplicada."); } if(action==="requires") return prepared(prepareEmergencyAction({actor:actor(),action:"manage-emergency-response"}),""); }
function setup() { $("#emergency-role").addEventListener("change",e=>{role=e.target.value; $("#report-form").reset(); roleInfo(); render(); message();}); $("#search").addEventListener("input",e=>{query=e.target.value;render();}); [["#status-filter",v=>statusFilter=v],["#severity-filter",v=>severityFilter=v],["#type-filter",v=>typeFilter=v]].forEach(([sel,set])=>$(sel).addEventListener("change",e=>{set(e.target.value);render();})); $("#report-form").addEventListener("submit",e=>{e.preventDefault(); if(role==="ADMIN") return message("Esta operación requiere fuente institucional.","error"); const f=new FormData(e.currentTarget); prepared(prepareEmergencyReport({actor:actor(),reporterId:actor().id,type:f.get("type"),severity:f.get("severity"),location:f.get("location"),title:f.get("title"),description:f.get("description")}),"Reporte DEMO preparado — no enviado ni almacenado.");}); $("#requires-source").addEventListener("click",()=>handle("requires")); $("#close-dialog").addEventListener("click",()=>$("#detail-dialog").close()); document.addEventListener("click",e=>{const b=e.target.closest("[data-action]");if(b)handle(b.dataset.action,b.dataset.id);}); }
function init(){renderTypeFilter();roleInfo();statistics();render();setup();} init();
